export EDITOR="nvim"
export BUN_INSTALL="/home/jackson/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_DIR="$HOME/.local/share"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
