return {
	"nvim-lua/plenary.nvim",
	"mbbill/undotree",
	"nvim-tree/nvim-web-devicons",
	"folke/which-key.nvim",
	"gitsigns.nvim",
	"folke/todo-comments.nvim",
	"stevearc/dressing.nvim",
	"akinsho/bufferline.nvim",
	{ "echasnovski/mini.surround", version = false, config = true },
	{ "echasnovski/mini.indentscope", version = false, config = true },
	-- { "echasnovski/mini.comment", version = false, config = true },
	{ "numToStr/Comment.nvim", lazy = false, config = true },
	{ "echasnovski/mini.pairs", version = false, config = true },
	{ "folke/todo-comments.nvim", config = true },
}
