# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 2
final_space: true
console_title_template: "{{ .Shell }} in {{ .Folder }}"

blocks:
- type: prompt
  alignment: left
  newline: true
  segments:
  - type: path
    style: plain
    # leading_diamond: ◖
    # trailing_diamond: ◗
    background: transparent
    foreground: blue
    template: "{{ .Path }}"
    properties:
      style: full

  - type: git
    style: plain
    foreground: darkGray
    background: transparent
    template: " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}"
    properties:
      branch_icon: ""
      fetch_status: true
      commit_icon: "@"

- type: rprompt
  overflow: hidden
  segments:
  - type: executiontime
    style: plain
    foreground: yellow
    background: transparent
    template: "{{ .FormattedMs }}"

- type: prompt
  alignment: left
  newline: true
  segments:
  - type: text
    style: plain
    foreground: cyan
    background: transparent
    foreground_templates:
    - "{{if gt .Code 0}}red{{end}}"
    - "{{if eq .Code 0}}cyan{{end}}"
    template: "❯"

transient_prompt:
  foreground: cyan
  background: transparent
  foreground_templates:
  - "{{if gt .Code 0}}red{{end}}"
  - "{{if eq .Code 0}}cyan{{end}}"
  template: "❯ "
